-- 회원기본
CREATE TABLE MEMBERS (
	MNO      INTEGER      NOT NULL COMMENT '회원일련번호', -- 회원일련번호
	EMAIL    VARCHAR(40)  NOT NULL COMMENT '이메일', -- 이메일
	PWD      VARCHAR(100) NOT NULL COMMENT '암호', -- 암호
	MNAME    VARCHAR(50)  NOT NULL COMMENT '이름', -- 이름
	CRE_DATE DATETIME     NOT NULL COMMENT '가입일', -- 가입일
	MOD_DATE DATETIME     NOT NULL COMMENT '마지막암호변경일', -- 마지막암호변경일
	SEX      VARCHAR(10)  NOT NULL COMMENT '성별', -- 성별
	P_NUM    VARCHAR(15)  NOT NULL COMMENT '폰번호', -- 핸드폰번호
	HOBBY    VARCHAR(20)  NOT NULL COMMENT '취미', -- 취미
	AGE      INTEGER      NOT NULL COMMENT '나이', -- 나이
	POINT    INTEGER      DEFAULT 500 COMMENT '포인트' -- 포인트
)
COMMENT '회원기본';

-- 회원기본
ALTER TABLE MEMBERS
	ADD CONSTRAINT PK_MEMBERS -- 회원기본 기본키
		PRIMARY KEY (
			MNO -- 회원일련번호
		);

-- 회원기본 유니크 인덱스
CREATE UNIQUE INDEX UIX_MEMBERS
	ON MEMBERS ( -- 회원기본
		EMAIL ASC -- 이메일
	);

ALTER TABLE MEMBERS
	MODIFY COLUMN MNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '회원일련번호';
	
INSERT INTO MEMBERS(EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE,SEX,P_NUM,HOBBY,AGE)
VALUES ('s1@test.com','1111','홍길동',NOW(),NOW(),'남자','010-1234-5678','축구',20);

INSERT INTO MEMBERS(EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE,SEX,P_NUM,HOBBY,AGE)
VALUES ('s2@test.com','1111','임꺽정',NOW(),NOW(),'남자','010-1234-5678','축구',20);

INSERT INTO MEMBERS(EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE,SEX,P_NUM,HOBBY,AGE)
VALUES ('s3@test.com','1111','일지매',NOW(),NOW(),'남자','010-1234-5678','축구',20);

INSERT INTO MEMBERS(EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE,SEX,P_NUM,HOBBY,AGE)
VALUES ('s4@test.com','1111','이몽룡',NOW(),NOW(),'남자','010-1234-5678','축구',20);

INSERT INTO MEMBERS(EMAIL,PWD,MNAME,CRE_DATE,MOD_DATE,SEX,P_NUM,HOBBY,AGE)
VALUES ('s5@test.com','1111','성춘향',NOW(),NOW(),'여자','010-1234-5678','십자수',20);	

SELECT * FROM MEMBERS;